---
tiller:
  image: gcr.io/kubernetes-helm/tiller
  tag: v2.8.1
  tillerUserServiceAccountName: jenkins
  tillerUserServiceAccountNamespace: dt-ftth-cicd
projects:
  flux:
    description: |-
      GitOps with Helm and Weave Flux
    tiller: true
    editAccess: true
    rootUser: true
rootUser:
  enable: true
  name: useroot
